import {createRequire} from 'node:module';
import {homedir} from 'node:os';
import {mkdir,writeFile} from 'node:fs/promises';
const require=createRequire(import.meta.url);
const {chromium}=require(`${homedir()}/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright`);
const output=process.argv[2]??'/tmp/portfolio-review';await mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),results=[];
const base=process.env.TOWN_URL||'http://127.0.0.1:5173';
try{
 for(const [name,width,height] of [['desktop',1440,900],['tablet',820,1000],['mobile',390,844],['small',320,700]]){
  const page=await browser.newPage({viewport:{width,height},reducedMotion:'reduce'}),errors=[];
  page.on('pageerror',error=>errors.push(String(error)));
  await page.goto(base);
  await page.locator('.portfolio-header').waitFor();await page.evaluate(()=>document.fonts.ready);
  if(await page.locator('.town-invitation').count())throw new Error('Duplicate town invitation remains');
  if(await page.locator('.portfolio-content-surface #work').count()!==1||await page.locator('.portfolio-opening #home').count()!==1)throw new Error('Opening and content are not separate');
  const initial=await page.evaluate(()=>({pageWidth:document.documentElement.scrollWidth,viewport:innerWidth,height:document.body.scrollHeight,cards:document.querySelectorAll('.portfolio-project').length,hidden:document.querySelector('#town-experience').hidden,htmlOverflow:getComputedStyle(document.documentElement).overflow,bodyOverflow:getComputedStyle(document.body).overflow}));
  if(initial.pageWidth>width+1||initial.cards!==5||!initial.hidden)throw new Error(`${name}: initial page failed ${JSON.stringify(initial)}`);
  await page.waitForFunction(()=>document.querySelector('#hero-world-view').dataset.live==='true',null,{timeout:90000});
  if(await page.locator('#town-canvas').evaluate(el=>el.parentElement.id)!=='hero-world-view')throw new Error('Hero is not using the live renderer');
  if(await page.evaluate(()=>JSON.parse(localStorage.getItem('davstep.choice-planet.v3')).order.length))throw new Error('Preview changed game progress');
  await page.locator('.portfolio-page img').evaluateAll(async images=>{images.forEach(img=>img.loading='eager');await Promise.all(images.map(img=>img.decode()));});
  await page.screenshot({path:`${output}/${name}-home.png`});
  await page.screenshot({path:`${output}/${name}-full.png`,fullPage:true});
  await page.locator('.portfolio-header a[href="#work"]').click();
  await page.locator('#project-outpost').screenshot({path:`${output}/${name}-project.png`});
  await page.locator('#about').scrollIntoViewIfNeeded();
  const scrollBefore=await page.evaluate(()=>scrollY);
  await page.locator('.hero-world-entry').evaluate(button=>button.click());
  await page.locator('body.game-playing').waitFor({timeout:90000});
  await page.locator('#game-hud').waitFor();
  const cardOverflow=await page.locator('.game-card-label').evaluateAll(labels=>labels.some(label=>label.scrollWidth>label.clientWidth+1));
  if(cardOverflow)throw new Error(`${name}: idea labels overflow their cards`);
  await page.screenshot({path:`${output}/${name}-game.png`});
  await page.locator('[data-idea="settlers"]').click();
  await page.waitForFunction(()=>JSON.parse(localStorage.getItem('davstep.choice-planet.v3')).order.includes('settlers'));
  await page.locator('#brand').click();
  await page.locator('#portfolio').waitFor();
  const restored=await page.evaluate(()=>({scroll:scrollY,overflow:getComputedStyle(document.documentElement).overflow,order:JSON.parse(localStorage.getItem('davstep.choice-planet.v3')).order,frame:window.__townDebug?.town?.renderer.info.render.frame??null}));
  if(Math.abs(restored.scroll-scrollBefore)>2||!restored.order.includes('settlers')||restored.overflow==='hidden')throw new Error(`Return failed ${JSON.stringify(restored)} vs ${scrollBefore}`);
  await page.waitForTimeout(300);
  if(restored.frame!==null&&await page.evaluate(()=>window.__townDebug.town.renderer.info.render.frame)!==restored.frame)throw new Error('Renderer is still running on portfolio');
  const orderLength=restored.order.length;
  await page.keyboard.press('1');
  if(await page.evaluate(()=>JSON.parse(localStorage.getItem('davstep.choice-planet.v3')).order.length)!==orderLength)throw new Error('Portfolio key selected an idea');
  await page.screenshot({path:`${output}/${name}-after-return.png`,fullPage:true});
  if(await page.evaluate(()=>document.documentElement.scrollWidth)>width+1)throw new Error('Return introduced horizontal overflow');
  await page.reload();await page.locator('.portfolio-header').waitFor();
  if(await page.locator('#town-experience').isVisible())throw new Error('Reload hid portfolio behind saved game');
  await page.locator('.hero-world-entry').click();await page.locator('body.game-playing').waitFor({timeout:90000});
  if(await page.evaluate(()=>JSON.parse(localStorage.getItem('davstep.choice-planet.v3')).order.length)!==orderLength)throw new Error('Resume lost saved choices');
  await page.locator('.chrome [data-panel="work"]').click();
  await page.locator('#content-panel.open').waitFor();await page.keyboard.press('Escape');await page.locator('#content-panel').waitFor({state:'hidden'});
  if(!await page.locator('#town-experience').isVisible()||await page.locator('#content-panel').isVisible())throw new Error('Escape from panel left game');
  await page.keyboard.press('Escape');await page.locator('#portfolio').waitFor();
  await page.locator('.portfolio-header a[href="#about"]').click();
  const aboutTop=await page.locator('#about').evaluate(el=>el.getBoundingClientRect().top);
  if(aboutTop<-2||aboutTop>height)throw new Error('About navigation did not scroll');
  await page.locator('.hero-world-entry').evaluate(button=>button.click());await page.locator('body.game-playing').waitFor();
  await page.goBack();await page.locator('#portfolio').waitFor();
  if(await page.locator('#town-experience').isVisible())throw new Error('Browser Back did not return to the page');
  await page.goForward();await page.locator('body.game-playing').waitFor();
  await page.keyboard.press('Escape');await page.locator('#portfolio').waitFor();
  await page.locator('.portfolio-header a[href="#contact"]').click();
  await page.locator('[data-copy-discord]').click();
  await page.waitForFunction(()=>document.querySelector('#contact-status').textContent.length>0);
  if(!await page.locator('#contact-status').textContent())throw new Error('No Discord feedback');
  results.push({name,initial,restored,errors});if(errors.length)throw new Error(errors.join('\n'));
  await page.close();
 }
 const deep=await browser.newPage({reducedMotion:'reduce'});await deep.goto(base+'/#town/project-wizard');await deep.locator('#content-panel.open').waitFor({timeout:90000});
 if(await deep.locator('#panel-title').textContent()!=='Idle Wizard')throw new Error('Direct project link failed');await deep.close();
 const failed=await browser.newPage();await failed.route(/town\/main\.ts|main-.*\.js/,route=>route.abort());await failed.goto(base);await failed.locator('.hero-world-entry').click();
 await failed.waitForFunction(()=>document.querySelector('#town-load-status').textContent.includes('could not open'));
 if(!await failed.locator('#portfolio').isVisible())throw new Error('A failed game load hid the page');await failed.close();
 const fallback=await browser.newPage({reducedMotion:'reduce'});await fallback.goto(base+'/?fallback=1#town');await fallback.locator('body.game-playing').waitFor({timeout:90000});await fallback.locator('[data-idea="settlers"]').click();
 await fallback.waitForFunction(()=>JSON.parse(localStorage.getItem('davstep.choice-planet.v3')).order.includes('settlers'));await fallback.locator('#brand').click();await fallback.locator('#portfolio').waitFor();await fallback.close();
 const nojs=await browser.newPage({javaScriptEnabled:false,viewport:{width:390,height:844}});await nojs.goto(base);
 if(await nojs.locator('.portfolio-project').count()!==5)throw new Error('Projects need JS to read');
 await nojs.screenshot({path:`${output}/no-js.png`,fullPage:true});await nojs.close();
}finally{await writeFile(`${output}/results.json`,JSON.stringify(results,null,2));await browser.close();}
console.log(JSON.stringify(results));
